// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://planetscale.com
// Generated: 2026-06-25T08:31:33.192Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#414141' | '#0b6ec5' | '#c1c1c1' | '#737373' | '#ffffff' | '#000000' | '#111111' | '#f35815' | '#f2b600' | '#ebebeb';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = never;
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700';

export type SpacingToken = '4px' | '80px' | '96px';

export type RadiusToken = '9999px';

export type DurationToken = '150ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
