// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://replit.com
// Generated: 2026-06-25T08:29:30.219Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#404040' | '#000000' | '#595959' | '#0051c3' | '#ffffff' | '#ebebeb' | '#de5052' | '#521010';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '600';

export type SpacingToken = '3px' | '23px' | '53px' | '160px';

export type RadiusToken = '2px' | '5px';

export type DurationToken = '150ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
