// Generated by designlang v7.0.0
// Source: https://resend.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFD6EBFD);
  static const Color actionSecondary = Color(0xFF00A3FF);
  static const Color surfaceDefault = Color(0xFF000000);
  static const Color textBody = Color(0xFFFFFFFF);
  static const double spacingS0 = 1;
  static const double spacingS1 = 20;
  static const double spacingS2 = 24;
  static const double spacingS3 = 28;
  static const double spacingS4 = 40;
  static const double spacingS5 = 48;
  static const double spacingS6 = 62;
  static const double spacingS7 = 80;
  static const double spacingS8 = 96;
  static const double spacingS9 = 104;
  static const double spacingS10 = 144;
  static const double spacingS11 = 150;
  static const double spacingS12 = 221;
  static const double spacingS13 = 380;
  static const double radiusR0 = 4;
  static const double radiusR1 = 8;
  static const double radiusR2 = 12;
  static const double radiusR3 = 16;
  static const double radiusR4 = 24;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFD6EBFD);
  static const Color brandSecondary = Color(0xFF00A3FF);
  static const Color neutralN100 = Color(0xFFF0F0F0);
  static const Color neutralN200 = Color(0xFFA1A4A5);
  static const Color neutralN300 = Color(0xFFFFFFFF);
  static const Color neutralN400 = Color(0xFFF1F7FE);
  static const Color neutralN500 = Color(0xFF464A4D);
  static const Color neutralN600 = Color(0xFF6C6C6C);
  static const Color neutralN700 = Color(0xFF000000);
  static const Color neutralN800 = Color(0xFFE5EDFD);
  static const Color neutralN900 = Color(0xFF70757E);
  static const Color neutralN1000 = Color(0xFF262A2D);
  static const Color neutralN1100 = Color(0xFFCCCCCC);
  static const Color backgroundBg0 = Color(0xFF000000);
  static const Color backgroundBg1 = Color(0xFFFFFFFF);
  static const Color textText0 = Color(0xFFFFFFFF);
  static const Color textText1 = Color(0xFFF0F0F0);
  static const Color textText2 = Color(0xFFF1F7FE);
  static const Color textText3 = Color(0xFFA1A4A5);
  static const Color textText4 = Color(0xFFFFC446);
  static const Color textText5 = Color(0xFFFCFDFF);
  static const Color textText6 = Color(0xFFEBECED);
  static const Color textText7 = Color(0xFF464A4D);
  static const Color textText8 = Color(0xFF6C6C6C);
  static const Color textText9 = Color(0xFFA0A0A0);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
