// Generated by designlang v7.0.0
// Source: https://planetscale.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFF2B600);
  static const Color actionSecondary = Color(0xFFF35815);
  static const Color surfaceDefault = Color(0xFFFAFAFA);
  static const Color textBody = Color(0xFF414141);
  static const double spacingS0 = 4;
  static const double spacingS1 = 80;
  static const double spacingS2 = 96;
  static const double radiusR0 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFF2B600);
  static const Color brandSecondary = Color(0xFFF35815);
  static const Color neutralN100 = Color(0xFF414141);
  static const Color neutralN200 = Color(0xFFC1C1C1);
  static const Color neutralN300 = Color(0xFF737373);
  static const Color neutralN400 = Color(0xFFFFFFFF);
  static const Color neutralN500 = Color(0xFF000000);
  static const Color neutralN600 = Color(0xFF111111);
  static const Color neutralN700 = Color(0xFFEBEBEB);
  static const Color backgroundBg0 = Color(0xFFFAFAFA);
  static const Color backgroundBg1 = Color(0xFF111111);
  static const Color textText0 = Color(0xFF414141);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFF111111);
  static const Color textText3 = Color(0xFFC1C1C1);
  static const Color textText4 = Color(0xFF000000);
  static const Color textText5 = Color(0xFF0B6EC5);
  static const Color textText6 = Color(0xFF737373);
  static const Color textText7 = Color(0xFFFAFAFA);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
