// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://sentry.io
// Generated: 2026-06-25T08:30:25.845Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#ffffff' | '#d4d4d4' | '#e1e4e8' | '#f97583' | '#9ecbff' | '#6a5fc1' | '#b392f0' | '#150f23' | '#79b8ff' | '#6a737d' | '#000000' | '#4e2a9a' | '#85e89d' | '#1f1633' | '#fd44b0' | '#c2ef4e' | '#dbedff' | '#1a1a1a' | '#efefef' | '#7553ff' | '#ffab70' | '#362d59' | '#090d16' | '#2d2340' | '#422082' | '#fdaeb7' | '#79628c' | '#584674' | '#c1c1c1';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Rubik' | 'Monaco' | 'IBM Plex Mono' | 'Dammit Sans';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600';

export type SpacingToken = '2px' | '16px' | '20px' | '24px' | '32px' | '35px' | '40px' | '44px' | '56px' | '64px' | '72px' | '83px' | '160px';

export type RadiusToken = '2px' | '6px' | '10px' | '13px' | '16px' | '50px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '600ms' | '800ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
