// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://render.com
// Generated: 2026-06-25T08:30:10.009Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#e3e3e3' | '#0d0d0d' | '#ffffff' | '#000000' | '#8a05ff' | '#6b6b6b' | '#4d4d4d' | '#e7dbff' | '#33acff' | '#006d4c' | '#d67f2e' | '#f347ff' | '#e96770' | '#48008c' | '#9b52fb' | '#faefe5' | '#dffeed' | '#e0f4ff' | '#fce2fe' | '#009e7a' | '#fce9ea' | '#272727' | '#180d43' | '#f680ff' | '#0088e5' | '#c29800' | '#5dc70a' | '#8f8f8f' | '#c2eaff' | '#f4f0ff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'PPNeueMontreal' | 'Roobert' | 'Helvetica' | 'PPNeueMontrealMono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '300';

export type SpacingToken = '1px' | '48px' | '56px' | '72px' | '80px' | '86px' | '120px' | '160px' | '166px' | '201px' | '213px' | '270px' | '287px' | '295px' | '305px' | '312px' | '323px' | '460px' | '467px' | '481px';

export type RadiusToken = '2px' | '50px' | '937px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
