// Generated by designlang v7.0.0
// Source: https://sentry.io
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF150F23);
  static const Color actionSecondary = Color(0xFF9ECBFF);
  static const Color surfaceDefault = Color(0xFF1F1633);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 2;
  static const double spacingS1 = 16;
  static const double spacingS2 = 20;
  static const double spacingS3 = 24;
  static const double spacingS4 = 32;
  static const double spacingS5 = 35;
  static const double spacingS6 = 40;
  static const double spacingS7 = 44;
  static const double spacingS8 = 56;
  static const double spacingS9 = 64;
  static const double spacingS10 = 72;
  static const double spacingS11 = 83;
  static const double spacingS12 = 160;
  static const double radiusR0 = 2;
  static const double radiusR1 = 6;
  static const double radiusR2 = 10;
  static const double radiusR3 = 13;
  static const double radiusR4 = 16;
  static const double radiusR5 = 50;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF150F23);
  static const Color brandSecondary = Color(0xFF9ECBFF);
  static const Color neutralN100 = Color(0xFFFFFFFF);
  static const Color neutralN200 = Color(0xFFD4D4D4);
  static const Color neutralN300 = Color(0xFFE1E4E8);
  static const Color neutralN400 = Color(0xFF6A737D);
  static const Color neutralN500 = Color(0xFF000000);
  static const Color neutralN600 = Color(0xFF1A1A1A);
  static const Color neutralN700 = Color(0xFFEFEFEF);
  static const Color neutralN800 = Color(0xFF584674);
  static const Color neutralN900 = Color(0xFFC1C1C1);
  static const Color backgroundBg0 = Color(0xFF1F1633);
  static const Color backgroundBg1 = Color(0xFF150F23);
  static const Color backgroundBg2 = Color(0xFF422082);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFF1A1A1A);
  static const Color textText3 = Color(0xFF6A5FC1);
  static const Color textText4 = Color(0xFF1F1633);
  static const Color textText5 = Color(0xFF03060A);
  static const Color textText6 = Color(0xFF4E2A9A);
  static const Color textText7 = Color(0xFF010205);
  static const Color textText8 = Color(0xFF090D16);
  static const Color textText9 = Color(0xFFEFEFEF);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
