// Generated by designlang v7.0.0
// Source: https://cal.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF0000EE)
    val ActionSecondary = Color(0xFF0099FF)
    val SurfaceDefault = Color(0xFFF4F4F4)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF0000EE)
    val BrandSecondary = Color(0xFF0099FF)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFF242424)
    val NeutralN300 = Color(0xFF898989)
    val NeutralN400 = Color(0xFFE5E7EB)
    val NeutralN500 = Color(0xFFFFFFFF)
    val NeutralN600 = Color(0xFF111111)
    val NeutralN700 = Color(0xFFF4F4F4)
    val NeutralN800 = Color(0xFF374151)
    val NeutralN900 = Color(0xFFD3D3D3)
    val NeutralN1000 = Color(0xFF808080)
    val NeutralN1100 = Color(0xFF4C5A70)
    val NeutralN1200 = Color(0xFF6B7280)
    val NeutralN1300 = Color(0xFF9CA3AF)
    val NeutralN1400 = Color(0xFF767676)
    val BackgroundBg0 = Color(0xFFF4F4F4)
    val BackgroundBg1 = Color(0xFFFFFFFF)
    val BackgroundBg2 = Color(0xFFF8F9FA)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFF0000EE)
    val TextText3 = Color(0xFF292929)
    val TextText4 = Color(0xFF111111)
    val TextText5 = Color(0xFF242424)
    val TextText6 = Color(0xFF898989)
    val TextText7 = Color(0xFF101010)
    val TextText8 = Color(0xFF6B7280)
    val TextText9 = Color(0xFF9CA3AF)
    val SpacingS0 = 1.dp
    val SpacingS1 = 40.dp
    val SpacingS2 = 48.dp
    val SpacingS3 = 80.dp
    val SpacingS4 = 96.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 6.dp
    val RadiusR2 = 10.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 29.dp
    val RadiusR5 = 40.dp
    val RadiusR6 = 100.dp
    val RadiusR7 = 120.dp
    val RadiusR8 = 1000.dp
    val RadiusR9 = 1250.dp
    val RadiusR10 = 9999.dp
}
