// Framer Motion emitter — `<host>-motion.framer.js`.
//
// Turns the extracted durations + easing curves into ready-to-import
// Framer Motion `transition` presets and a few common `variants`
// (fade, slide-up, scale-in, stagger). Framer Motion is the dominant
// React animation library, so this is the highest-leverage motion
// emitter for the React ecosystem.
//
// v12.16 — now also emits:
//   • spring presets derived from detected overshoot beziers
//   • whileInView variants when the source uses scroll/view-timeline
//   • keyframe variants reconstructed from on-page @keyframes

function bezier(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return [parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]), parseFloat(m[4])];
  const named = {
    linear: [0, 0, 1, 1], ease: [0.25, 0.1, 0.25, 1],
    'ease-in': [0.42, 0, 1, 1], 'ease-out': [0, 0, 0.58, 1], 'ease-in-out': [0.42, 0, 0.58, 1],
  };
  return named[String(raw).trim()] || null;
}

function camel(s) {
  return String(s || '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&');
}

// Rough inverse of a critically-damped second-order response.
// Shorter durations → stiffer; deeper overshoot → less damping.
// Same heuristic the Motion One emitter uses, kept in sync for parity.
function springFromBezier(pts, ms) {
  const [, y1, , y2] = pts;
  const overshoot = Math.max(0, Math.max(y1 - 1, y2 - 1, -y1, -y2));
  const seconds = Math.max(0.1, (ms || 400) / 1000);
  const stiffness = Math.round(Math.min(700, Math.max(80, 600 / seconds)));
  const damping = Math.round(Math.max(8, 30 - overshoot * 40));
  return { stiffness, damping, mass: 1 };
}

export function formatFramerMotion(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];
  const springs   = Array.isArray(design?.motion?.springs)   ? design.motion.springs   : [];
  const keyframes = Array.isArray(design?.motion?.keyframes) ? design.motion.keyframes : [];
  const scroll    = design?.motion?.scrollLinked || { present: false, signals: [] };

  // Pick a default duration (the most common "medium" feel) and easing.
  const durSec = (d) => ((d.ms || parseInt(d.css || d.value || d, 10) || 300) / 1000);
  const defaultDur = durations.length
    ? durSec(durations[Math.min(2, durations.length - 1)])
    : 0.3;
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));
  const defaultEase = bezier(sortedEase[0]?.raw) || [0.25, 1, 0.5, 1];

  const lines = [
    '// Framer Motion presets — generated by designlang (motionlang)',
    `// Source: ${design?.meta?.url || host}`,
    `// ${new Date().toISOString()}`,
    '//',
    '//   import { transitions, variants } from \'./' + host + '-motion.framer\';',
    '//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"',
    '//               transition={transitions.base} />',
    '',
    '/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */',
    'export const easings = {',
  ];

  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const pts = bezier(e.raw);
    if (!pts) return;
    const key = e.family && e.family !== 'custom' ? camel(e.family) : `custom${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, pts, raw: e.raw, count: e.count });
  });
  if (easeEntries.length === 0) {
    easeEntries.push({ key: 'standard', pts: defaultEase, raw: 'fallback', count: 0 });
  }
  for (const { key, pts, count } of easeEntries) {
    lines.push(`  ${key}: [${pts.join(', ')}],${count ? ` // ${count}× on page` : ''}`);
  }
  lines.push('};', '');

  lines.push('/** Duration presets (seconds), extracted from the live page. */');
  lines.push('export const durations = {');
  if (durations.length) {
    for (const d of durations) {
      const name = camel(d.name || `ms${d.ms}`);
      lines.push(`  ${name}: ${durSec(d)},`);
    }
  } else {
    lines.push('  fast: 0.15,', '  base: 0.3,', '  slow: 0.5,');
  }
  lines.push('};', '');

  // Spring presets — derived from detected overshoot beziers when present,
  // else a single tasteful default so consumers can always reach for one.
  const springEntries = [];
  springs.forEach((s, i) => {
    const pts = bezier(s.raw);
    if (!pts) return;
    springEntries.push({ key: i === 0 ? 'soft' : `spring${i + 1}`, opts: springFromBezier(pts, defaultDur * 1000) });
  });
  if (springEntries.length === 0) {
    springEntries.push({ key: 'soft', opts: { stiffness: 320, damping: 30, mass: 1 } });
  }
  const primarySpringKey = springEntries[0].key;

  lines.push('/** Spring presets — pass to a Framer Motion `transition` prop. */');
  lines.push('export const springs = {');
  for (const { key, opts } of springEntries) {
    lines.push(`  ${key}: { type: 'spring', stiffness: ${opts.stiffness}, damping: ${opts.damping}, mass: ${opts.mass} },`);
  }
  lines.push('};', '');

  const primaryEaseKey = easeEntries[0].key;
  lines.push('/** Ready-to-spread Framer Motion transition objects. */');
  lines.push('export const transitions = {');
  lines.push(`  base:  { duration: ${defaultDur}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  fast:  { duration: ${Math.max(0.1, defaultDur * 0.5).toFixed(3)}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  slow:  { duration: ${(defaultDur * 1.8).toFixed(3)}, ease: easings.${primaryEaseKey} },`);
  lines.push(`  spring: springs.${primarySpringKey},`);
  lines.push('};', '');

  lines.push('/** Common variants wired to the extracted timing. */');
  lines.push('export const variants = {');
  lines.push('  fade: {');
  lines.push('    hidden: { opacity: 0 },');
  lines.push('    show:   { opacity: 1, transition: transitions.base },');
  lines.push('  },');
  lines.push('  slideUp: {');
  lines.push('    hidden: { opacity: 0, y: 16 },');
  lines.push('    show:   { opacity: 1, y: 0, transition: transitions.base },');
  lines.push('  },');
  lines.push('  scaleIn: {');
  lines.push('    hidden: { opacity: 0, scale: 0.96 },');
  lines.push('    show:   { opacity: 1, scale: 1, transition: transitions.base },');
  lines.push('  },');
  lines.push('  pop: {');
  lines.push('    hidden: { opacity: 0, scale: 0.9 },');
  lines.push(`    show:   { opacity: 1, scale: 1, transition: springs.${primarySpringKey} },`);
  lines.push('  },');
  lines.push('  stagger: {');
  lines.push('    hidden: {},');
  lines.push('    show:   { transition: { staggerChildren: ' + Math.max(0.04, defaultDur * 0.25).toFixed(3) + ' } },');
  lines.push('  },');

  // Reconstructed keyframe variants — Framer Motion accepts arrays per
  // property to produce keyframe animations. We use the camelCased
  // @keyframes name so the source intent survives.
  const usedKeyframes = keyframes.filter(k => k.used && k.steps && k.steps.length);
  for (const kf of usedKeyframes.slice(0, 8)) {
    const propMap = {};
    for (const step of kf.steps) {
      for (const part of (step.style || '').split(';')) {
        const [p, v] = part.split(':').map(s => (s || '').trim());
        if (!p || !v) continue;
        (propMap[p] ||= []).push(v);
      }
    }
    const entries = Object.entries(propMap)
      .filter(([, vals]) => vals.length >= 2)
      .map(([prop, vals]) => `      ${JSON.stringify(camel(prop))}: ${JSON.stringify(vals)}`);
    if (!entries.length) continue;
    lines.push(`  ${camel(kf.name)}: {`);
    lines.push('    hidden: {},');
    lines.push('    show: {');
    lines.push(entries.join(',\n') + ',');
    lines.push('      transition: transitions.base,');
    lines.push('    },');
    lines.push('  },');
  }

  lines.push('};', '');

  if (scroll.present) {
    lines.push('/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */');
    lines.push('export const inView = {');
    lines.push('  fadeIn: {');
    lines.push('    initial: variants.fade.hidden,');
    lines.push('    whileInView: variants.fade.show,');
    lines.push('    viewport: { once: true, amount: 0.3 },');
    lines.push('  },');
    lines.push('  riseIn: {');
    lines.push('    initial: variants.slideUp.hidden,');
    lines.push('    whileInView: variants.slideUp.show,');
    lines.push('    viewport: { once: true, amount: 0.3 },');
    lines.push('  },');
    lines.push('};', '');
  }

  lines.push(`export default { easings, durations, springs, transitions, variants${scroll.present ? ', inView' : ''} };`);
  lines.push('');

  return lines.join('\n');
}
