// Gallery formatter — render the gallery model (src/gallery) as a static site:
// an index grid of score cards and one permalink page per clone, each with OG
// tags so a shared link unfurls the measured score. Pure string builders;
// renderGallerySite() returns a [{ path, content }] list the CLI writes out.

import { formatFidelityCard } from './fidelity-report.js';

const GRADE_COLORS = {
  A: '#0a8a52', B: '#1f6feb', C: '#b08400', D: '#d2691e', F: '#c43d3d', unknown: '#555',
};

function band(n) {
  if (n == null) return '#888';
  if (n >= 90) return '#16a34a';
  if (n >= 75) return '#65a30d';
  if (n >= 55) return '#d97706';
  return '#dc2626';
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

const SHELL_CSS = `
  :root { --bg:#0d0d0f; --panel:#17171b; --line:#27272d; --fg:#f4f4f5; --mut:#8a8a93; }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--fg); font: 15px/1.6 -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
  a { color: inherit; text-decoration: none; }
  .wrap { max-width: 1100px; margin: 0 auto; padding: 56px 24px 80px; }
  .kicker { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; letter-spacing: 2px; color: var(--mut); }
  h1 { font-size: 34px; margin: 8px 0 4px; letter-spacing: -0.02em; }
  .lede { color: var(--mut); margin: 0 0 36px; }
  .stats { display: flex; gap: 28px; flex-wrap: wrap; margin: 0 0 40px; }
  .stat .n { font-size: 30px; font-weight: 800; }
  .stat .l { font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: 1.5px; color: var(--mut); text-transform: uppercase; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 18px; }
  .card { background: var(--panel); border: 1px solid var(--line); border-radius: 16px; padding: 22px; transition: border-color .15s, transform .15s; }
  .card:hover { border-color: #3a3a42; transform: translateY(-2px); }
  .card .host { font-size: 19px; font-weight: 700; margin-bottom: 14px; word-break: break-all; }
  .card .score { display: flex; align-items: baseline; gap: 10px; }
  .card .score .n { font-size: 52px; font-weight: 800; line-height: 1; }
  .pill { display: inline-block; min-width: 30px; text-align: center; padding: 4px 10px; border-radius: 8px; color: #fff; font-weight: 800; }
  .split { font-family: ui-monospace, monospace; font-size: 12px; color: var(--mut); margin-top: 14px; }
  footer { color: var(--mut); font-size: 13px; margin-top: 56px; }
`;

export function formatGalleryIndex(gallery, opts = {}) {
  const { items, stats } = gallery;
  const title = opts.title || 'Fidelity Gallery';
  const cards = items.map(it => `
      <a class="card" href="${esc(it.slug)}/">
        <div class="host">${esc(it.host)}</div>
        <div class="score">
          <span class="n" style="color:${band(it.overall)}">${it.overall ?? '—'}</span>
          <span class="pill" style="background:${GRADE_COLORS[it.grade] || GRADE_COLORS.unknown}">${esc(it.grade === 'unknown' ? '?' : it.grade)}</span>
        </div>
        <div class="split">visual ${it.visual ?? '—'}% · motion ${it.motion ?? '—'}%${it.directiveCount ? ` · ${it.directiveCount} to fix` : ''}</div>
      </a>`).join('');

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${stats.count} measured clone(s), avg ${stats.avg ?? '—'}% fidelity.">
<style>${SHELL_CSS}</style></head>
<body><div class="wrap">
  <div class="kicker">DESIGNLANG · MEASURED CLONES</div>
  <h1>${esc(title)}</h1>
  <p class="lede">Every clone scored against its source — visuals pixel-diffed, motion compared. No claims, just numbers.</p>
  <div class="stats">
    <div class="stat"><div class="n">${stats.count}</div><div class="l">clones</div></div>
    <div class="stat"><div class="n">${stats.avg ?? '—'}</div><div class="l">avg fidelity</div></div>
    <div class="stat"><div class="n">${stats.best ? esc(stats.best.grade) : '—'}</div><div class="l">best grade</div></div>
  </div>
  <div class="grid">${cards || '<p class="lede">No clones yet. Run <code>designlang fidelity</code> first.</p>'}</div>
  <footer>Generated by designlang · fidelity gallery</footer>
</div></body></html>`;
}

export function formatGalleryItemPage(item, opts = {}) {
  const cardPath = 'card.svg';
  const desc = `${item.overall ?? '—'}% fidelity clone of ${item.host} (${item.grade}) — visual ${item.visual ?? '—'}%, motion ${item.motion ?? '—'}%.`;
  const ogImage = opts.baseUrl ? `${opts.baseUrl.replace(/\/$/, '')}/${item.slug}/${cardPath}` : cardPath;

  const motionRows = (item.motionAspects || []).map(a =>
    `<tr><td>${esc(a.aspect)}</td><td>${Math.round((a.score ?? 0) * 100)}%</td></tr>`).join('');

  const directives = (item.directives || []).map(d =>
    `<li><span class="tag">${esc(d.priority)}/${esc(d.area)}</span> ${esc(d.issue)}<div class="fix">${esc(d.fix)}</div></li>`).join('');

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(item.host)} · ${item.overall ?? '—'}% fidelity</title>
<meta property="og:title" content="${esc(item.host)} — ${item.overall ?? '—'}% fidelity clone">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${esc(ogImage)}">
<meta name="twitter:card" content="summary_large_image">
<style>${SHELL_CSS}
  .back { font-family: ui-monospace, monospace; font-size: 12px; color: var(--mut); }
  .card-embed { margin: 24px 0 8px; max-width: 520px; }
  table { width: 100%; max-width: 420px; border-collapse: collapse; font-family: ui-monospace, monospace; font-size: 13px; margin: 8px 0 28px; }
  td { padding: 7px 0; border-bottom: 1px solid var(--line); }
  td:last-child { text-align: right; color: var(--mut); }
  h2 { font-size: 18px; margin: 28px 0 12px; }
  ul.plan { list-style: none; padding: 0; }
  ul.plan li { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; padding: 14px 16px; margin-bottom: 10px; }
  .tag { font-family: ui-monospace, monospace; font-size: 11px; color: var(--mut); margin-right: 8px; }
  .fix { color: var(--mut); font-size: 13px; margin-top: 6px; }
  .links a { color: #6ea8fe; font-family: ui-monospace, monospace; font-size: 13px; margin-right: 18px; }
</style></head>
<body><div class="wrap">
  <a class="back" href="../">← gallery</a>
  <div class="card-embed">${formatFidelityCard(item)}</div>
  <div class="links">
    ${item.url ? `<a href="${esc(item.url)}" rel="noopener">source ↗</a>` : ''}
    ${item.cloneUrl ? `<a href="${esc(item.cloneUrl)}" rel="noopener">clone ↗</a>` : ''}
  </div>
  ${motionRows ? `<h2>Motion</h2><table>${motionRows}</table>` : ''}
  <h2>Correction plan</h2>
  ${directives ? `<ul class="plan">${directives}</ul>` : '<p class="lede">No corrections outstanding.</p>'}
  <footer>Generated by designlang · fidelity gallery</footer>
</div></body></html>`;
}

// Returns [{ path, content }] for the whole static site.
export function renderGallerySite(gallery, opts = {}) {
  const files = [{ path: 'index.html', content: formatGalleryIndex(gallery, opts) }];
  for (const item of gallery.items) {
    files.push({ path: `${item.slug}/index.html`, content: formatGalleryItemPage(item, opts) });
    files.push({ path: `${item.slug}/card.svg`, content: formatFidelityCard(item) });
  }
  return files;
}
