// Web Animations API emitter — `<host>-motion.waapi.js`.
//
// The zero-dependency sibling of the Motion One / Framer emitters. Everything
// here runs on the browser-native `Element.animate()` — no runtime, no bundle
// cost. WAAPI accepts cubic-bezier easing strings verbatim, so the extracted
// curves are reproduced *exactly* (no spring approximation, unlike the
// library targets).
//
// We emit:
//   • `easings`   — the page's cubic-bezier strings, keyed by family
//   • `durations` — extracted timings in milliseconds
//   • `keyframes` — keyframe arrays reconstructed from on-page @keyframes,
//                   ready to hand straight to `el.animate(frames, timing)`
//   • `animations`— fadeIn / slideUp / scaleIn … helpers returning the live
//                   Animation object so callers can await `.finished`
//   • a `prefersReducedMotion()` guard the helpers honour automatically.

function bezier(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return `cubic-bezier(${m[1]}, ${m[2]}, ${m[3]}, ${m[4]})`;
  const named = new Set(['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out']);
  return named.has(String(raw).trim()) ? String(raw).trim() : null;
}

function camel(s) {
  return String(s || '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&');
}

export function formatMotionWaapi(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];
  const springs   = Array.isArray(design?.motion?.springs)   ? design.motion.springs   : [];
  const keyframes = Array.isArray(design?.motion?.keyframes) ? design.motion.keyframes : [];

  const ms = (d) => (d.ms || parseInt(d.css || d.value || d, 10) || 300);
  const defaultDur = durations.length ? ms(durations[Math.min(2, durations.length - 1)]) : 300;

  // Easings: dedupe by family, keep the most-used first, fall back to a
  // standard curve when the page exposed nothing parseable.
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));
  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const css = bezier(e.raw);
    if (!css) return;
    const key = e.family && e.family !== 'custom' ? camel(e.family) : `custom${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, css, count: e.count });
  });
  // Detected overshoot beziers ride along as a `spring` easing (WAAPI honours
  // the overshoot natively — the curve simply leaves the [0,1] band).
  springs.forEach((s) => {
    const css = bezier(s.raw);
    if (css && !easeEntries.find((x) => x.key === 'spring')) easeEntries.push({ key: 'spring', css, count: s.count });
  });
  if (easeEntries.length === 0) {
    easeEntries.push({ key: 'standard', css: 'cubic-bezier(0.25, 0.1, 0.25, 1)', count: 0 });
  }
  const primaryEaseKey = easeEntries[0].key;

  const lines = [
    '// Web Animations API presets — generated by designlang (motionlang)',
    `// Source: ${design?.meta?.url || host}`,
    `// ${new Date().toISOString()}`,
    '//',
    '// Zero-dependency. Runs on the browser-native Element.animate().',
    `//   import { animations } from './${host}-motion.waapi.js';`,
    "//   animations.fadeIn(document.querySelector('#hero'));",
    "//   await animations.slideUp(card, { delay: 80 }).finished;",
    '',
    '/** Easing curves extracted from the live page, as WAAPI easing strings. */',
    'export const easings = {',
  ];
  for (const { key, css, count } of easeEntries) {
    lines.push(`  ${key}: '${css}',${count ? ` // ${count}× on page` : ''}`);
  }
  lines.push('};', '');

  lines.push('/** Duration presets (milliseconds), extracted from the live page. */');
  lines.push('export const durations = {');
  if (durations.length) {
    for (const d of durations) lines.push(`  ${camel(d.name || `ms${d.ms}`)}: ${ms(d)},`);
  } else {
    lines.push('  fast: 150,', '  base: 300,', '  slow: 500,');
  }
  lines.push('};', '');

  // Reconstructed keyframes — WAAPI takes an array of frame objects, so each
  // step's `prop: value` pairs become one frame.
  const usedKeyframes = keyframes.filter((k) => k.used && k.steps && k.steps.length);
  if (usedKeyframes.length) {
    lines.push('/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */');
    lines.push('export const keyframes = {');
    for (const kf of usedKeyframes.slice(0, 16)) {
      const frames = [];
      for (const step of kf.steps) {
        const frame = {};
        for (const part of (step.style || '').split(';')) {
          const [p, v] = part.split(':').map((x) => (x || '').trim());
          if (p && v) frame[camel(p)] = v;
        }
        const offset = parseFloat(String(step.offset)) / 100;
        if (Number.isFinite(offset)) frame.offset = offset;
        if (Object.keys(frame).length) frames.push(frame);
      }
      if (frames.length >= 2) lines.push(`  ${camel(kf.name)}: ${JSON.stringify(frames)},`);
    }
    lines.push('};', '');
  } else {
    lines.push('/** No on-page @keyframes were attached to elements; emit empty for shape parity. */');
    lines.push('export const keyframes = {};', '');
  }

  lines.push('/** Honours the user\'s reduced-motion preference. */');
  lines.push('export const prefersReducedMotion = () =>');
  lines.push("  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;");
  lines.push('');
  lines.push(`const _timing = { duration: ${defaultDur}, easing: easings.${primaryEaseKey}, fill: 'both' };`);
  lines.push('');
  lines.push('function _animate(el, frames, opts = {}) {');
  lines.push('  const timing = { ..._timing, ...opts };');
  lines.push('  if (prefersReducedMotion()) timing.duration = 0;');
  lines.push('  return el.animate(frames, timing);');
  lines.push('}');
  lines.push('');
  lines.push('/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */');
  lines.push('export const animations = {');
  lines.push('  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),');
  lines.push('  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),');
  lines.push("  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),");
  lines.push("  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),");
  lines.push("  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),");
  lines.push('};', '');

  lines.push('export default { easings, durations, keyframes, animations, prefersReducedMotion };');
  lines.push('');

  return lines.join('\n');
}
