// Motion One emitter — `<host>-motion.one.js`.
//
// Sibling of the Framer Motion emitter, targeting the `motion` package
// (a.k.a. Motion One / Motion for the Web) — a ~3kb library that wraps
// the Web Animations API and ships first-class spring + scroll helpers.
//
// We emit:
//   • `easings`   — cubic-bezier arrays keyed by classified family
//   • `durations` — extracted timings in seconds
//   • `springs`   — Motion One spring options (stiffness/damping/mass)
//                   derived from detected overshoot beziers; falls back
//                   to a sensible default when the site has no springs.
//   • `keyframes` — animation maps reconstructed from on-page @keyframes
//   • `animations`— ready-to-call wrappers around `animate()` so users
//                   can do `animations.fadeIn('#hero')` without thinking
//                   about timing.
//   • `inView` / `scroll` helpers when the site actually uses
//     scroll-/view-timeline.

function bezier(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return [parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]), parseFloat(m[4])];
  const named = {
    linear: [0, 0, 1, 1], ease: [0.25, 0.1, 0.25, 1],
    'ease-in': [0.42, 0, 1, 1], 'ease-out': [0, 0, 0.58, 1], 'ease-in-out': [0.42, 0, 0.58, 1],
  };
  return named[String(raw).trim()] || null;
}

function camel(s) {
  return String(s || '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&');
}

// Rough inverse of a critically-damped second-order response:
// shorter durations → stiffer, deeper overshoot → less damping.
// Not physically exact — just a useful starting point that matches feel.
function springFromBezier(pts, ms) {
  const [, y1, , y2] = pts;
  const overshoot = Math.max(0, Math.max(y1 - 1, y2 - 1, -y1, -y2));
  const seconds = Math.max(0.1, (ms || 400) / 1000);
  const stiffness = Math.round(Math.min(700, Math.max(80, 600 / seconds)));
  const damping = Math.round(Math.max(8, 30 - overshoot * 40));
  return { stiffness, damping, mass: 1 };
}

export function formatMotionOne(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];
  const springs   = Array.isArray(design?.motion?.springs)   ? design.motion.springs   : [];
  const keyframes = Array.isArray(design?.motion?.keyframes) ? design.motion.keyframes : [];
  const scroll    = design?.motion?.scrollLinked || { present: false, signals: [] };

  const durSec = (d) => ((d.ms || parseInt(d.css || d.value || d, 10) || 300) / 1000);
  const defaultDur = durations.length
    ? durSec(durations[Math.min(2, durations.length - 1)])
    : 0.3;

  // Easings: keep families by frequency, dedupe by family key, fall back to a
  // good Motion One default if the page didn't expose anything parseable.
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));
  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const pts = bezier(e.raw);
    if (!pts) return;
    const key = e.family && e.family !== 'custom' ? camel(e.family) : `custom${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, pts, count: e.count });
  });
  if (easeEntries.length === 0) {
    easeEntries.push({ key: 'standard', pts: [0.25, 0.1, 0.25, 1], count: 0 });
  }
  const primaryEaseKey = easeEntries[0].key;

  // Springs: derive Motion One options from any detected overshoot beziers.
  const springEntries = [];
  springs.forEach((s, i) => {
    const pts = bezier(s.raw);
    if (!pts) return;
    springEntries.push({ key: i === 0 ? 'soft' : `spring${i + 1}`, opts: springFromBezier(pts, defaultDur * 1000) });
  });
  if (springEntries.length === 0) {
    springEntries.push({ key: 'soft', opts: { stiffness: 320, damping: 30, mass: 1 } });
  }
  const primarySpringKey = springEntries[0].key;

  const lines = [
    '// Motion One presets — generated by designlang (motionlang)',
    `// Source: ${design?.meta?.url || host}`,
    `// ${new Date().toISOString()}`,
    '//',
    '//   import { animate } from \'motion\';',
    '//   import { animations, easings, durations } from \'./' + host + '-motion.one.js\';',
    '//',
    '//   animations.fadeIn(\'#hero\');',
    '//   animations.slideUp(\'.card\', { delay: 0.1 });',
    '',
    '/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */',
    'export const easings = {',
  ];
  for (const { key, pts, count } of easeEntries) {
    lines.push(`  ${key}: [${pts.join(', ')}],${count ? ` // ${count}× on page` : ''}`);
  }
  lines.push('};', '');

  lines.push('/** Duration presets (seconds), extracted from the live page. */');
  lines.push('export const durations = {');
  if (durations.length) {
    for (const d of durations) {
      const name = camel(d.name || `ms${d.ms}`);
      lines.push(`  ${name}: ${durSec(d)},`);
    }
  } else {
    lines.push('  fast: 0.15,', '  base: 0.3,', '  slow: 0.5,');
  }
  lines.push('};', '');

  lines.push('/** Motion One spring options — pass as the `type: \'spring\'` block of an animate() call. */');
  lines.push('export const springs = {');
  for (const { key, opts } of springEntries) {
    lines.push(`  ${key}: { type: 'spring', stiffness: ${opts.stiffness}, damping: ${opts.damping}, mass: ${opts.mass} },`);
  }
  lines.push('};', '');

  // Reconstructed keyframes — Motion One accepts arrays per-property, so
  // we flatten step values per property and emit a usable animation map.
  const usedKeyframes = keyframes.filter(k => k.used && k.steps && k.steps.length);
  if (usedKeyframes.length) {
    lines.push('/** @keyframes blocks reconstructed as Motion One keyframe maps. */');
    lines.push('export const keyframes = {');
    for (const kf of usedKeyframes.slice(0, 16)) {
      const propMap = {};
      for (const step of kf.steps) {
        for (const part of (step.style || '').split(';')) {
          const [p, v] = part.split(':').map(s => (s || '').trim());
          if (!p || !v) continue;
          (propMap[p] ||= []).push(v);
        }
      }
      const entries = Object.entries(propMap)
        .filter(([, vals]) => vals.length >= 2)
        .map(([prop, vals]) => `    ${JSON.stringify(camel(prop))}: ${JSON.stringify(vals)}`);
      if (!entries.length) continue;
      lines.push(`  ${camel(kf.name)}: {`);
      lines.push(entries.join(',\n'));
      lines.push('  },');
    }
    lines.push('};', '');
  } else {
    lines.push('/** No on-page @keyframes were attached to elements; emit empty for shape parity. */');
    lines.push('export const keyframes = {};', '');
  }

  lines.push('/** Animate-on-call helpers. Each takes a Motion One target + optional override. */');
  lines.push('import { animate } from \'motion\';');
  lines.push('');
  lines.push('const _t = { duration: ' + defaultDur + ', easing: easings.' + primaryEaseKey + ' };');
  lines.push('');
  lines.push('export const animations = {');
  lines.push('  fadeIn: (target, opts = {}) =>');
  lines.push('    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),');
  lines.push('  fadeOut: (target, opts = {}) =>');
  lines.push('    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),');
  lines.push('  slideUp: (target, opts = {}) =>');
  lines.push('    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),');
  lines.push('  slideDown: (target, opts = {}) =>');
  lines.push('    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),');
  lines.push('  scaleIn: (target, opts = {}) =>');
  lines.push('    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),');
  lines.push('  pop: (target, opts = {}) =>');
  lines.push('    animate(target, { scale: [0.9, 1] }, { ...springs.' + primarySpringKey + ', ...opts }),');
  lines.push('};', '');

  if (scroll.present) {
    lines.push('/** Site uses scroll- or view-timeline. Helpers wired to Motion One\'s `inView` / `scroll`. */');
    lines.push('import { inView, scroll } from \'motion\';');
    lines.push('');
    lines.push('export const enterOnView = (target, variant = animations.slideUp) =>');
    lines.push('  inView(target, (el) => { variant(el.target); });');
    lines.push('');
    lines.push('export const parallaxY = (target, distance = 80) =>');
    lines.push('  scroll(animate(target, { y: [0, -distance] }, { easing: \'linear\' }));');
    lines.push('');
  }

  lines.push('export default { easings, durations, springs, keyframes, animations };');
  lines.push('');

  return lines.join('\n');
}
