// GSAP emitter — `<host>-motion.gsap.js`.
//
// Targets GreenSock (gsap). The extracted cubic-bezier curves are registered
// as named `CustomEase`s (so the site's exact feel is reproducible), durations
// come through as seconds, and we emit `gsap.from()` reveal helpers plus a
// ScrollTrigger reveal when the page actually uses scroll-/view-timeline.
//
// We emit:
//   • `eases`       — CustomEase SVG-path strings keyed by family
//   • `durations`   — extracted timings in seconds
//   • `registerEases(gsap)` — registers every ease as a named CustomEase
//   • `reveals`     — gsap.from() helpers (fadeIn / slideUp / scaleIn / pop)
//   • `revealOnScroll()` — ScrollTrigger batch reveal (only when scroll-linked)

function bezierPts(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return [parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3]), parseFloat(m[4])];
  const named = {
    linear: [0, 0, 1, 1], ease: [0.25, 0.1, 0.25, 1],
    'ease-in': [0.42, 0, 1, 1], 'ease-out': [0, 0, 0.58, 1], 'ease-in-out': [0.42, 0, 0.58, 1],
  };
  return named[String(raw).trim()] || null;
}

function camel(s) {
  return String(s || '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&');
}

// GSAP CustomEase accepts SVG cubic-path data; a bezier from (0,0)→(1,1) with
// the two extracted control points maps directly to one cubic segment.
function customEasePath([x1, y1, x2, y2]) {
  return `M0,0 C${x1},${y1} ${x2},${y2} 1,1`;
}

export function formatMotionGsap(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];
  const springs   = Array.isArray(design?.motion?.springs)   ? design.motion.springs   : [];
  const scroll    = design?.motion?.scrollLinked || { present: false, signals: [] };

  const durSec = (d) => ((d.ms || parseInt(d.css || d.value || d, 10) || 300) / 1000);
  const defaultDur = durations.length ? durSec(durations[Math.min(2, durations.length - 1)]) : 0.3;

  // Eases: dedupe by family, most-used first, fall back to a standard curve.
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));
  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const pts = bezierPts(e.raw);
    if (!pts) return;
    const key = e.family && e.family !== 'custom' ? camel(e.family) : `custom${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, path: customEasePath(pts), count: e.count });
  });
  springs.forEach((s) => {
    const pts = bezierPts(s.raw);
    if (pts && !easeEntries.find((x) => x.key === 'spring')) {
      easeEntries.push({ key: 'spring', path: customEasePath(pts), count: s.count });
    }
  });
  if (easeEntries.length === 0) {
    easeEntries.push({ key: 'standard', path: customEasePath([0.25, 0.1, 0.25, 1]), count: 0 });
  }
  const primaryEaseKey = easeEntries[0].key;

  const lines = [
    '// GSAP presets — generated by designlang (motionlang)',
    `// Source: ${design?.meta?.url || host}`,
    `// ${new Date().toISOString()}`,
    '//',
    "//   import gsap from 'gsap';",
    `//   import { registerEases, reveals } from './${host}-motion.gsap.js';`,
    '//   registerEases(gsap);            // one-time: registers CustomEases',
    "//   reveals.slideUp('.card');",
    '',
    '/** CustomEase path data extracted from the live page, keyed by family. */',
    'export const eases = {',
  ];
  for (const { key, path, count } of easeEntries) {
    lines.push(`  ${key}: '${path}',${count ? ` // ${count}× on page` : ''}`);
  }
  lines.push('};', '');

  lines.push('/** Duration presets (seconds), extracted from the live page. */');
  lines.push('export const durations = {');
  if (durations.length) {
    for (const d of durations) lines.push(`  ${camel(d.name || `ms${d.ms}`)}: ${durSec(d)},`);
  } else {
    lines.push('  fast: 0.15,', '  base: 0.3,', '  slow: 0.5,');
  }
  lines.push('};', '');

  lines.push('/** Register every extracted curve as a named GSAP CustomEase. Call once. */');
  lines.push('export function registerEases(gsap) {');
  lines.push('  const CustomEase = gsap.plugins?.CustomEase || (typeof window !== \'undefined\' && window.CustomEase);');
  lines.push('  if (!CustomEase) {');
  lines.push("    console.warn('[motion.gsap] CustomEase plugin not registered — call gsap.registerPlugin(CustomEase) first.');");
  lines.push('    return;');
  lines.push('  }');
  lines.push('  for (const [name, path] of Object.entries(eases)) CustomEase.create(name, path);');
  lines.push('}');
  lines.push('');

  lines.push('/** gsap.from() reveal helpers. Pass any GSAP target + optional vars override. */');
  lines.push('export const reveals = {');
  lines.push(`  fadeIn: (target, vars = {}) => gsap.from(target, { opacity: 0, duration: ${defaultDur}, ease: '${primaryEaseKey}', ...vars }),`);
  lines.push(`  slideUp: (target, vars = {}) => gsap.from(target, { opacity: 0, y: 24, duration: ${defaultDur}, ease: '${primaryEaseKey}', ...vars }),`);
  lines.push(`  slideDown: (target, vars = {}) => gsap.from(target, { opacity: 0, y: -24, duration: ${defaultDur}, ease: '${primaryEaseKey}', ...vars }),`);
  lines.push(`  scaleIn: (target, vars = {}) => gsap.from(target, { opacity: 0, scale: 0.96, duration: ${defaultDur}, ease: '${primaryEaseKey}', ...vars }),`);
  lines.push(`  pop: (target, vars = {}) => gsap.from(target, { scale: 0.9, duration: ${defaultDur}, ease: '${easeEntries.find((e) => e.key === 'spring') ? 'spring' : primaryEaseKey}', ...vars }),`);
  lines.push('};', '');

  if (scroll.present) {
    lines.push('/** Site uses scroll-/view-timeline. Batch-reveals elements as they enter. */');
    lines.push('/** Requires: gsap.registerPlugin(ScrollTrigger). */');
    lines.push('export function revealOnScroll(targets, vars = {}) {');
    lines.push('  return gsap.utils.toArray(targets).map((el) =>');
    lines.push('    gsap.from(el, {');
    lines.push(`      opacity: 0, y: 24, duration: ${defaultDur}, ease: '${primaryEaseKey}', ...vars,`);
    lines.push("      scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none reverse' },");
    lines.push('    }));');
    lines.push('}');
    lines.push('');
  }

  lines.push('export default { eases, durations, registerEases, reveals };');
  lines.push('');

  return lines.join('\n');
}
