// Render a verify report as JSON and a self-contained HTML triptych
// (original │ rebuilt │ diff-heatmap per component) with the fidelity score.

export function formatVerifyJson(report) {
  // Drop the verbose per-property deltas from JSON; keep the attribution summary.
  const slim = {
    ...report,
    components: report.components.map(({ deltas, ...c }) => c), // eslint-disable-line no-unused-vars
  };
  return JSON.stringify(slim, null, 2) + '\n';
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

function band(n) {
  if (n == null) return '#888';
  if (n >= 90) return '#16a34a';
  if (n >= 75) return '#65a30d';
  if (n >= 55) return '#d97706';
  return '#dc2626';
}

export function formatVerifyHtml(report) {
  const score = report.fidelity;
  const cards = report.components.map((c) => {
    if (c.status !== 'ok') {
      return `<div class="comp na"><div class="comp-head"><span class="kind">${esc(c.component)}</span><span class="tag">${esc(c.status)}</span></div><p class="reason">${esc(c.reason || '')}</p></div>`;
    }
    const attr = (c.attribution || []).map((a) =>
      `<li><b>${esc(a.family)}</b> — ${a.unmapped ? `${a.unmapped} unmapped` : ''}${a.unmapped && a.moves ? ', ' : ''}${a.moves ? `${a.moves} shifted` : ''}</li>`).join('');
    return `<div class="comp">
      <div class="comp-head"><span class="kind">${esc(c.component)}</span><span class="score" style="color:${band(c.fidelity)}">${c.fidelity}<small>/100</small></span></div>
      <div class="trip">
        <figure><img src="verify/original/${esc(c.component)}.png" alt="original"><figcaption>original</figcaption></figure>
        <figure><img src="verify/rebuilt/${esc(c.component)}.png" alt="rebuilt from tokens"><figcaption>rebuilt from tokens</figcaption></figure>
        <figure><img src="verify/diff/${esc(c.component)}.png" alt="diff"><figcaption>loss heatmap</figcaption></figure>
      </div>
      ${attr ? `<ul class="attr">${attr}</ul>` : '<p class="attr none">no significant token loss</p>'}
    </div>`;
  }).join('');

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>designlang · fidelity · ${esc(report.host)}</title>
<style>
  :root { --fg:#111; --mut:#666; --line:#e5e5e5; --bg:#fafafa; }
  * { box-sizing: border-box; }
  body { font: 15px/1.6 -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: var(--fg); background: var(--bg); margin: 0; padding: 40px 24px; }
  .wrap { max-width: 1080px; margin: 0 auto; }
  h1 { font-size: 28px; margin: 0 0 4px; }
  .sub { color: var(--mut); font-size: 13px; margin: 0 0 28px; }
  .big { display: flex; align-items: baseline; gap: 14px; margin: 0 0 32px; }
  .big .n { font-size: 64px; font-weight: 800; line-height: 1; color: ${band(score)}; }
  .big .l { color: var(--mut); font-size: 13px; text-transform: uppercase; letter-spacing: .08em; }
  .comp { background: #fff; border: 1px solid var(--line); border-radius: 12px; padding: 18px; margin-bottom: 18px; }
  .comp.na { opacity: .7; }
  .comp-head { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 14px; }
  .kind { font-weight: 700; text-transform: capitalize; }
  .score { font-size: 26px; font-weight: 800; } .score small { font-size: 12px; color: var(--mut); font-weight: 500; }
  .tag { font: 11px/1 ui-monospace, monospace; text-transform: uppercase; letter-spacing: .1em; color: var(--mut); border: 1px solid var(--line); padding: 4px 8px; border-radius: 6px; }
  .trip { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
  figure { margin: 0; text-align: center; } figure img { max-width: 100%; border: 1px solid var(--line); border-radius: 8px; background: #fff; }
  figcaption { color: var(--mut); font-size: 11px; margin-top: 6px; text-transform: uppercase; letter-spacing: .06em; }
  .attr { margin: 14px 0 0; padding-left: 18px; color: var(--mut); font-size: 13px; } .attr.none { list-style: none; padding: 0; font-style: italic; }
  .reason { color: var(--mut); font-size: 13px; margin: 0; }
  footer { color: var(--mut); font-size: 12px; margin-top: 24px; }
</style></head>
<body><div class="wrap">
  <h1>Fidelity report — ${esc(report.host)}</h1>
  <p class="sub">How faithfully the extracted tokens reconstruct the live components. ${esc(report.generatedAt)}</p>
  <div class="big"><span class="n">${score == null ? '—' : score}</span><span class="l">${score == null ? 'no components scored' : 'site fidelity / 100'}</span></div>
  ${cards}
  <footer>Rebuilt using only designlang's extracted tokens. Lower scores point to where tokenization lost information — see the heatmaps. Generated by <b>designlang verify</b>.</footer>
</div></body></html>`;
}
