// Generated by designlang v7.0.0
// Source: https://ramp.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF000000);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 8;
  static const double spacingS1 = 13;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF000000);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color textText0 = Color(0xFF000000);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
    ),
  );
}
