// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://cal.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x0000EE)
  static let actionSecondary = Color(hex: 0x0099FF)
  static let surfaceDefault = Color(hex: 0xF4F4F4)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 40
  static let spacingS2: CGFloat = 48
  static let spacingS3: CGFloat = 80
  static let spacingS4: CGFloat = 96

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 6
  static let radiusR2: CGFloat = 10
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 29
  static let radiusR5: CGFloat = 40
  static let radiusR6: CGFloat = 100
  static let radiusR7: CGFloat = 120
  static let radiusR8: CGFloat = 1000
  static let radiusR9: CGFloat = 1250
  static let radiusR10: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x0000EE)
  static let brandSecondary = Color(hex: 0x0099FF)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0x242424)
  static let neutralN300 = Color(hex: 0x898989)
  static let neutralN400 = Color(hex: 0xE5E7EB)
  static let neutralN500 = Color(hex: 0xFFFFFF)
  static let neutralN600 = Color(hex: 0x111111)
  static let neutralN700 = Color(hex: 0xF4F4F4)
  static let neutralN800 = Color(hex: 0x374151)
  static let neutralN900 = Color(hex: 0xD3D3D3)
  static let neutralN1000 = Color(hex: 0x808080)
  static let neutralN1100 = Color(hex: 0x4C5A70)
  static let neutralN1200 = Color(hex: 0x6B7280)
  static let neutralN1300 = Color(hex: 0x9CA3AF)
  static let neutralN1400 = Color(hex: 0x767676)
  static let backgroundBg0 = Color(hex: 0xF4F4F4)
  static let backgroundBg1 = Color(hex: 0xFFFFFF)
  static let backgroundBg2 = Color(hex: 0xF8F9FA)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x0000EE)
  static let textText3 = Color(hex: 0x292929)
  static let textText4 = Color(hex: 0x111111)
  static let textText5 = Color(hex: 0x242424)
  static let textText6 = Color(hex: 0x898989)
  static let textText7 = Color(hex: 0x101010)
  static let textText8 = Color(hex: 0x6B7280)
  static let textText9 = Color(hex: 0x9CA3AF)
}

// typography.body: family=Inter size=64px weight=600 lineHeight=70.4px
