// Generated by designlang v7.0.0
// Source: https://replit.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF0051C3);
  static const Color actionSecondary = Color(0xFFDE5052);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 3;
  static const double spacingS1 = 23;
  static const double spacingS2 = 53;
  static const double spacingS3 = 160;
  static const double radiusR0 = 2;
  static const double radiusR1 = 5;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF0051C3);
  static const Color brandSecondary = Color(0xFFDE5052);
  static const Color neutralN100 = Color(0xFF404040);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFF595959);
  static const Color neutralN400 = Color(0xFFFFFFFF);
  static const Color neutralN500 = Color(0xFFEBEBEB);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFFEBEBEB);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF404040);
  static const Color textText2 = Color(0xFFFFFFFF);
  static const Color textText3 = Color(0xFF595959);
  static const Color textText4 = Color(0xFF0051C3);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
