// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://webflow.com
// Generated: 2026-06-25T08:28:55.785Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#080808' | '#ffffff' | '#5a5a5a' | '#6ca7ff' | '#d8d8d8' | '#ffa666' | '#146ef5' | '#f0f0f0' | '#60ed76' | '#1a1a1a' | '#6b7280' | '#292929' | '#464646' | '#808080' | '#171717' | '#3b82f6' | '#363636';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'WF Visual Sans Variable' | 'WFVisualSans-Mono' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '550';

export type SpacingToken = '1px' | '23px' | '31px' | '37px' | '40px' | '46px' | '56px' | '64px' | '73px' | '80px' | '88px' | '91px' | '99px' | '111px' | '184px' | '192px' | '197px' | '215px' | '229px' | '248px' | '252px' | '380px';

export type RadiusToken = '2px' | '6px' | '50px' | '1280px';

export type DurationToken = '150ms' | '300ms' | '450ms' | '1200ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
