// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://resend.com
// Generated: 2026-06-25T08:26:02.771Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#f0f0f0' | '#a1a4a5' | '#ffffff' | '#f1f7fe' | '#464a4d' | '#6c6c6c' | '#d6ebfd' | '#44ffa4' | '#000000' | '#e5edfd' | '#ffc446' | '#70757e' | '#ff9592' | '#3b9eff' | '#baa7ff' | '#70b8ff' | '#ffca16' | '#22ff99' | '#262a2d' | '#0b0e14' | '#8354fe' | '#0077ff' | '#fa8200' | '#ff173f' | '#cccccc' | '#ff6465' | '#ffd60a' | '#00a3ff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'inter' | 'commitMono' | 'aBCFavorit' | 'Helvetica' | 'domaine' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700';

export type SpacingToken = '1px' | '20px' | '24px' | '28px' | '40px' | '48px' | '62px' | '80px' | '96px' | '104px' | '144px' | '150px' | '221px' | '380px';

export type RadiusToken = '4px' | '8px' | '12px' | '16px' | '24px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
