// Generated by designlang v7.0.0
// Source: https://render.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF8A05FF);
  static const Color actionSecondary = Color(0xFFE7DBFF);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 48;
  static const double spacingS2 = 56;
  static const double spacingS3 = 72;
  static const double spacingS4 = 80;
  static const double spacingS5 = 86;
  static const double spacingS6 = 120;
  static const double spacingS7 = 160;
  static const double spacingS8 = 166;
  static const double spacingS9 = 201;
  static const double spacingS10 = 213;
  static const double spacingS11 = 270;
  static const double spacingS12 = 287;
  static const double spacingS13 = 295;
  static const double spacingS14 = 305;
  static const double spacingS15 = 312;
  static const double spacingS16 = 323;
  static const double spacingS17 = 460;
  static const double spacingS18 = 467;
  static const double spacingS19 = 481;
  static const double radiusR0 = 2;
  static const double radiusR1 = 50;
  static const double radiusR2 = 937;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF8A05FF);
  static const Color brandSecondary = Color(0xFFE7DBFF);
  static const Color neutralN100 = Color(0xFFE3E3E3);
  static const Color neutralN200 = Color(0xFF0D0D0D);
  static const Color neutralN300 = Color(0xFFFFFFFF);
  static const Color neutralN400 = Color(0xFF000000);
  static const Color neutralN500 = Color(0xFF6B6B6B);
  static const Color neutralN600 = Color(0xFF4D4D4D);
  static const Color neutralN700 = Color(0xFFFCE9EA);
  static const Color neutralN800 = Color(0xFF272727);
  static const Color neutralN900 = Color(0xFF8F8F8F);
  static const Color neutralN1000 = Color(0xFFF4F0FF);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFF000000);
  static const Color backgroundBg2 = Color(0xFF141414);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFF0D0D0D);
  static const Color textText3 = Color(0xFF4D4D4D);
  static const Color textText4 = Color(0xFF6B6B6B);
  static const Color textText5 = Color(0xFF8A05FF);
  static const Color textText6 = Color(0xFF009E7A);
  static const Color textText7 = Color(0xFFD67F2E);
  static const Color textText8 = Color(0xFFF680FF);
  static const Color textText9 = Color(0xFF0088E5);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
