// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://render.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x8A05FF)
  static let actionSecondary = Color(hex: 0xE7DBFF)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 48
  static let spacingS2: CGFloat = 56
  static let spacingS3: CGFloat = 72
  static let spacingS4: CGFloat = 80
  static let spacingS5: CGFloat = 86
  static let spacingS6: CGFloat = 120
  static let spacingS7: CGFloat = 160
  static let spacingS8: CGFloat = 166
  static let spacingS9: CGFloat = 201
  static let spacingS10: CGFloat = 213
  static let spacingS11: CGFloat = 270
  static let spacingS12: CGFloat = 287
  static let spacingS13: CGFloat = 295
  static let spacingS14: CGFloat = 305
  static let spacingS15: CGFloat = 312
  static let spacingS16: CGFloat = 323
  static let spacingS17: CGFloat = 460
  static let spacingS18: CGFloat = 467
  static let spacingS19: CGFloat = 481

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 50
  static let radiusR2: CGFloat = 937
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x8A05FF)
  static let brandSecondary = Color(hex: 0xE7DBFF)
  static let neutralN100 = Color(hex: 0xE3E3E3)
  static let neutralN200 = Color(hex: 0x0D0D0D)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0x000000)
  static let neutralN500 = Color(hex: 0x6B6B6B)
  static let neutralN600 = Color(hex: 0x4D4D4D)
  static let neutralN700 = Color(hex: 0xFCE9EA)
  static let neutralN800 = Color(hex: 0x272727)
  static let neutralN900 = Color(hex: 0x8F8F8F)
  static let neutralN1000 = Color(hex: 0xF4F0FF)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let backgroundBg2 = Color(hex: 0x141414)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x0D0D0D)
  static let textText3 = Color(hex: 0x4D4D4D)
  static let textText4 = Color(hex: 0x6B6B6B)
  static let textText5 = Color(hex: 0x8A05FF)
  static let textText6 = Color(hex: 0x009E7A)
  static let textText7 = Color(hex: 0xD67F2E)
  static let textText8 = Color(hex: 0xF680FF)
  static let textText9 = Color(hex: 0x0088E5)
}

// typography.body: family=PPNeueMontreal size=80px weight=300 lineHeight=80px
