// Generated by designlang v7.0.0
// Source: https://webflow.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF146EF5)
    val ActionSecondary = Color(0xFF6CA7FF)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF146EF5)
    val BrandSecondary = Color(0xFF6CA7FF)
    val NeutralN100 = Color(0xFF080808)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF5A5A5A)
    val NeutralN400 = Color(0xFFD8D8D8)
    val NeutralN500 = Color(0xFFF0F0F0)
    val NeutralN600 = Color(0xFF1A1A1A)
    val NeutralN700 = Color(0xFF6B7280)
    val NeutralN800 = Color(0xFF292929)
    val NeutralN900 = Color(0xFF464646)
    val NeutralN1000 = Color(0xFF808080)
    val NeutralN1100 = Color(0xFF171717)
    val NeutralN1200 = Color(0xFF363636)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFF146EF5)
    val BackgroundBg2 = Color(0xFF080808)
    val BackgroundBg3 = Color(0xFF222222)
    val BackgroundBg4 = Color(0xFF171717)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF080808)
    val TextText2 = Color(0xFFFFFFFF)
    val TextText3 = Color(0xFF5A5A5A)
    val TextText4 = Color(0xFF808080)
    val TextText5 = Color(0xFFFFA666)
    val TextText6 = Color(0xFF6CA7FF)
    val TextText7 = Color(0xFF60ED76)
    val TextText8 = Color(0xFF146EF5)
    val TextText9 = Color(0xFF1A1A1A)
    val SpacingS0 = 1.dp
    val SpacingS1 = 23.dp
    val SpacingS2 = 31.dp
    val SpacingS3 = 37.dp
    val SpacingS4 = 40.dp
    val SpacingS5 = 46.dp
    val SpacingS6 = 56.dp
    val SpacingS7 = 64.dp
    val SpacingS8 = 73.dp
    val SpacingS9 = 80.dp
    val SpacingS10 = 88.dp
    val SpacingS11 = 91.dp
    val SpacingS12 = 99.dp
    val SpacingS13 = 111.dp
    val SpacingS14 = 184.dp
    val SpacingS15 = 192.dp
    val SpacingS16 = 197.dp
    val SpacingS17 = 215.dp
    val SpacingS18 = 229.dp
    val SpacingS19 = 248.dp
    val SpacingS20 = 252.dp
    val SpacingS21 = 380.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 6.dp
    val RadiusR2 = 50.dp
    val RadiusR3 = 1280.dp
}
