// Generated by designlang v7.0.0
// Source: https://render.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF8A05FF)
    val ActionSecondary = Color(0xFFE7DBFF)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF8A05FF)
    val BrandSecondary = Color(0xFFE7DBFF)
    val NeutralN100 = Color(0xFFE3E3E3)
    val NeutralN200 = Color(0xFF0D0D0D)
    val NeutralN300 = Color(0xFFFFFFFF)
    val NeutralN400 = Color(0xFF000000)
    val NeutralN500 = Color(0xFF6B6B6B)
    val NeutralN600 = Color(0xFF4D4D4D)
    val NeutralN700 = Color(0xFFFCE9EA)
    val NeutralN800 = Color(0xFF272727)
    val NeutralN900 = Color(0xFF8F8F8F)
    val NeutralN1000 = Color(0xFFF4F0FF)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFF000000)
    val BackgroundBg2 = Color(0xFF141414)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFF0D0D0D)
    val TextText3 = Color(0xFF4D4D4D)
    val TextText4 = Color(0xFF6B6B6B)
    val TextText5 = Color(0xFF8A05FF)
    val TextText6 = Color(0xFF009E7A)
    val TextText7 = Color(0xFFD67F2E)
    val TextText8 = Color(0xFFF680FF)
    val TextText9 = Color(0xFF0088E5)
    val SpacingS0 = 1.dp
    val SpacingS1 = 48.dp
    val SpacingS2 = 56.dp
    val SpacingS3 = 72.dp
    val SpacingS4 = 80.dp
    val SpacingS5 = 86.dp
    val SpacingS6 = 120.dp
    val SpacingS7 = 160.dp
    val SpacingS8 = 166.dp
    val SpacingS9 = 201.dp
    val SpacingS10 = 213.dp
    val SpacingS11 = 270.dp
    val SpacingS12 = 287.dp
    val SpacingS13 = 295.dp
    val SpacingS14 = 305.dp
    val SpacingS15 = 312.dp
    val SpacingS16 = 323.dp
    val SpacingS17 = 460.dp
    val SpacingS18 = 467.dp
    val SpacingS19 = 481.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 50.dp
    val RadiusR2 = 937.dp
}
