// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://ramp.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x000000)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 8
  static let spacingS1: CGFloat = 13

  // MARK: Primitive radius
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x000000)
  static let neutralN100 = Color(hex: 0x000000)
  static let textText0 = Color(hex: 0x000000)
}

// typography.body: family=Times size=16px weight=400 lineHeight=normal
