// Generated by designlang v7.0.0
// Source: https://duolingo.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFD7FFB8)
    val ActionSecondary = Color(0xFF0000EE)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFD7FFB8)
    val BrandSecondary = Color(0xFF0000EE)
    val NeutralN100 = Color(0xFF3C3C3C)
    val NeutralN200 = Color(0xFF777777)
    val NeutralN300 = Color(0xFF000000)
    val NeutralN400 = Color(0xFF4B4B4B)
    val NeutralN500 = Color(0xFFAFAFAF)
    val NeutralN600 = Color(0xFFFFFFFF)
    val NeutralN700 = Color(0xFFE5E5E5)
    val NeutralN800 = Color(0xFF808080)
    val NeutralN900 = Color(0xFFC1C1C1)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFFDDF4FF)
    val BackgroundBg2 = Color(0xFF100F3E)
    val BackgroundBg3 = Color(0xFF58CC02)
    val BackgroundBg4 = Color(0xFF000000)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF3C3C3C)
    val TextText2 = Color(0xFF0000EE)
    val TextText3 = Color(0xFFAFAFAF)
    val TextText4 = Color(0xFF4B4B4B)
    val TextText5 = Color(0xFFFFFFFF)
    val TextText6 = Color(0xFF1CB0F6)
    val TextText7 = Color(0xFF777777)
    val TextText8 = Color(0xFF58CC02)
    val TextText9 = Color(0xFF042C60)
    val SpacingS0 = 1.dp
    val SpacingS1 = 8.dp
    val SpacingS2 = 23.dp
    val SpacingS3 = 40.dp
    val SpacingS4 = 48.dp
    val SpacingS5 = 64.dp
    val SpacingS6 = 80.dp
    val SpacingS7 = 96.dp
    val SpacingS8 = 140.dp
    val SpacingS9 = 185.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 12.dp
}
