// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://duolingo.com
// Generated: 2026-06-25T08:27:36.320Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#3c3c3c' | '#777777' | '#000000' | '#a5ed6e' | '#4b4b4b' | '#58cc02' | '#afafaf' | '#1cb0f6' | '#d7ffb8' | '#ffffff' | '#0000ee' | '#000437' | '#042c60' | '#e5e5e5' | '#ddf4ff' | '#100f3e' | '#808080' | '#c1c1c1';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'duolingo-sans';
export type FontSizeToken   = never;
export type FontWeightToken = '500' | '700' | '400';

export type SpacingToken = '1px' | '8px' | '23px' | '40px' | '48px' | '64px' | '80px' | '96px' | '140px' | '185px';

export type RadiusToken = '2px' | '12px';

export type DurationToken = '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
