// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://replit.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x0051C3)
  static let actionSecondary = Color(hex: 0xDE5052)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 3
  static let spacingS1: CGFloat = 23
  static let spacingS2: CGFloat = 53
  static let spacingS3: CGFloat = 160

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 5
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x0051C3)
  static let brandSecondary = Color(hex: 0xDE5052)
  static let neutralN100 = Color(hex: 0x404040)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0x595959)
  static let neutralN400 = Color(hex: 0xFFFFFF)
  static let neutralN500 = Color(hex: 0xEBEBEB)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0xEBEBEB)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x404040)
  static let textText2 = Color(hex: 0xFFFFFF)
  static let textText3 = Color(hex: 0x595959)
  static let textText4 = Color(hex: 0x0051C3)
}

// typography.body: family=Times size=60px weight=300 lineHeight=72px
