// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://planetscale.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xF2B600)
  static let actionSecondary = Color(hex: 0xF35815)
  static let surfaceDefault = Color(hex: 0xFAFAFA)
  static let textBody = Color(hex: 0x414141)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 4
  static let spacingS1: CGFloat = 80
  static let spacingS2: CGFloat = 96

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xF2B600)
  static let brandSecondary = Color(hex: 0xF35815)
  static let neutralN100 = Color(hex: 0x414141)
  static let neutralN200 = Color(hex: 0xC1C1C1)
  static let neutralN300 = Color(hex: 0x737373)
  static let neutralN400 = Color(hex: 0xFFFFFF)
  static let neutralN500 = Color(hex: 0x000000)
  static let neutralN600 = Color(hex: 0x111111)
  static let neutralN700 = Color(hex: 0xEBEBEB)
  static let backgroundBg0 = Color(hex: 0xFAFAFA)
  static let backgroundBg1 = Color(hex: 0x111111)
  static let textText0 = Color(hex: 0x414141)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x111111)
  static let textText3 = Color(hex: 0xC1C1C1)
  static let textText4 = Color(hex: 0x000000)
  static let textText5 = Color(hex: 0x0B6EC5)
  static let textText6 = Color(hex: 0x737373)
  static let textText7 = Color(hex: 0xFAFAFA)
}

// typography.body: family=system-ui size=16px weight=400 lineHeight=24px
