// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://duolingo.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xD7FFB8)
  static let actionSecondary = Color(hex: 0x0000EE)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 8
  static let spacingS2: CGFloat = 23
  static let spacingS3: CGFloat = 40
  static let spacingS4: CGFloat = 48
  static let spacingS5: CGFloat = 64
  static let spacingS6: CGFloat = 80
  static let spacingS7: CGFloat = 96
  static let spacingS8: CGFloat = 140
  static let spacingS9: CGFloat = 185

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 12
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xD7FFB8)
  static let brandSecondary = Color(hex: 0x0000EE)
  static let neutralN100 = Color(hex: 0x3C3C3C)
  static let neutralN200 = Color(hex: 0x777777)
  static let neutralN300 = Color(hex: 0x000000)
  static let neutralN400 = Color(hex: 0x4B4B4B)
  static let neutralN500 = Color(hex: 0xAFAFAF)
  static let neutralN600 = Color(hex: 0xFFFFFF)
  static let neutralN700 = Color(hex: 0xE5E5E5)
  static let neutralN800 = Color(hex: 0x808080)
  static let neutralN900 = Color(hex: 0xC1C1C1)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0xDDF4FF)
  static let backgroundBg2 = Color(hex: 0x100F3E)
  static let backgroundBg3 = Color(hex: 0x58CC02)
  static let backgroundBg4 = Color(hex: 0x000000)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x3C3C3C)
  static let textText2 = Color(hex: 0x0000EE)
  static let textText3 = Color(hex: 0xAFAFAF)
  static let textText4 = Color(hex: 0x4B4B4B)
  static let textText5 = Color(hex: 0xFFFFFF)
  static let textText6 = Color(hex: 0x1CB0F6)
  static let textText7 = Color(hex: 0x777777)
  static let textText8 = Color(hex: 0x58CC02)
  static let textText9 = Color(hex: 0x042C60)
}

// typography.body: family=duolingo-sans size=64px weight=700 lineHeight=normal
