// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://cal.com
// Generated: 2026-06-25T08:26:30.335Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#242424' | '#898989' | '#e5e7eb' | '#ffffff' | '#111111' | '#f4f4f4' | '#374151' | '#d3d3d3' | '#808080' | '#4c5a70' | '#0ea5e9' | '#6701e6' | '#6b7280' | '#9ca3af' | '#0099ff' | '#7826b1' | '#aa61f1' | '#e9ddfd' | '#882c2f' | '#d85b5f' | '#0261a2' | '#f8d7d8' | '#d6ecfe' | '#767676';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Cal Sans UI Variable Light' | 'Times' | 'Cal Sans' | 'Matter Regular' | 'Matter Medium' | 'Matter SemiBold' | 'Roboto Mono' | 'CUSTOMV2;Cal Sans UI Regular';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '500' | '600';

export type SpacingToken = '1px' | '40px' | '48px' | '80px' | '96px';

export type RadiusToken = '2px' | '6px' | '10px' | '16px' | '29px' | '40px' | '100px' | '120px' | '1000px' | '1250px' | '9999px';

export type DurationToken = '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
