// Generated by designlang v7.0.0
// Source: https://resend.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFD6EBFD)
    val ActionSecondary = Color(0xFF00A3FF)
    val SurfaceDefault = Color(0xFF000000)
    val TextBody = Color(0xFFFFFFFF)
    val BrandPrimary = Color(0xFFD6EBFD)
    val BrandSecondary = Color(0xFF00A3FF)
    val NeutralN100 = Color(0xFFF0F0F0)
    val NeutralN200 = Color(0xFFA1A4A5)
    val NeutralN300 = Color(0xFFFFFFFF)
    val NeutralN400 = Color(0xFFF1F7FE)
    val NeutralN500 = Color(0xFF464A4D)
    val NeutralN600 = Color(0xFF6C6C6C)
    val NeutralN700 = Color(0xFF000000)
    val NeutralN800 = Color(0xFFE5EDFD)
    val NeutralN900 = Color(0xFF70757E)
    val NeutralN1000 = Color(0xFF262A2D)
    val NeutralN1100 = Color(0xFFCCCCCC)
    val BackgroundBg0 = Color(0xFF000000)
    val BackgroundBg1 = Color(0xFFFFFFFF)
    val TextText0 = Color(0xFFFFFFFF)
    val TextText1 = Color(0xFFF0F0F0)
    val TextText2 = Color(0xFFF1F7FE)
    val TextText3 = Color(0xFFA1A4A5)
    val TextText4 = Color(0xFFFFC446)
    val TextText5 = Color(0xFFFCFDFF)
    val TextText6 = Color(0xFFEBECED)
    val TextText7 = Color(0xFF464A4D)
    val TextText8 = Color(0xFF6C6C6C)
    val TextText9 = Color(0xFFA0A0A0)
    val SpacingS0 = 1.dp
    val SpacingS1 = 20.dp
    val SpacingS2 = 24.dp
    val SpacingS3 = 28.dp
    val SpacingS4 = 40.dp
    val SpacingS5 = 48.dp
    val SpacingS6 = 62.dp
    val SpacingS7 = 80.dp
    val SpacingS8 = 96.dp
    val SpacingS9 = 104.dp
    val SpacingS10 = 144.dp
    val SpacingS11 = 150.dp
    val SpacingS12 = 221.dp
    val SpacingS13 = 380.dp
    val RadiusR0 = 4.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 12.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 24.dp
}
