// Generated by designlang v7.0.0
// Source: https://cal.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF0000EE);
  static const Color actionSecondary = Color(0xFF0099FF);
  static const Color surfaceDefault = Color(0xFFF4F4F4);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 40;
  static const double spacingS2 = 48;
  static const double spacingS3 = 80;
  static const double spacingS4 = 96;
  static const double radiusR0 = 2;
  static const double radiusR1 = 6;
  static const double radiusR2 = 10;
  static const double radiusR3 = 16;
  static const double radiusR4 = 29;
  static const double radiusR5 = 40;
  static const double radiusR6 = 100;
  static const double radiusR7 = 120;
  static const double radiusR8 = 1000;
  static const double radiusR9 = 1250;
  static const double radiusR10 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF0000EE);
  static const Color brandSecondary = Color(0xFF0099FF);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFF242424);
  static const Color neutralN300 = Color(0xFF898989);
  static const Color neutralN400 = Color(0xFFE5E7EB);
  static const Color neutralN500 = Color(0xFFFFFFFF);
  static const Color neutralN600 = Color(0xFF111111);
  static const Color neutralN700 = Color(0xFFF4F4F4);
  static const Color neutralN800 = Color(0xFF374151);
  static const Color neutralN900 = Color(0xFFD3D3D3);
  static const Color neutralN1000 = Color(0xFF808080);
  static const Color neutralN1100 = Color(0xFF4C5A70);
  static const Color neutralN1200 = Color(0xFF6B7280);
  static const Color neutralN1300 = Color(0xFF9CA3AF);
  static const Color neutralN1400 = Color(0xFF767676);
  static const Color backgroundBg0 = Color(0xFFF4F4F4);
  static const Color backgroundBg1 = Color(0xFFFFFFFF);
  static const Color backgroundBg2 = Color(0xFFF8F9FA);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFF0000EE);
  static const Color textText3 = Color(0xFF292929);
  static const Color textText4 = Color(0xFF111111);
  static const Color textText5 = Color(0xFF242424);
  static const Color textText6 = Color(0xFF898989);
  static const Color textText7 = Color(0xFF101010);
  static const Color textText8 = Color(0xFF6B7280);
  static const Color textText9 = Color(0xFF9CA3AF);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
