// Generated by designlang v7.0.0
// Source: https://webflow.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF146EF5);
  static const Color actionSecondary = Color(0xFF6CA7FF);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 23;
  static const double spacingS2 = 31;
  static const double spacingS3 = 37;
  static const double spacingS4 = 40;
  static const double spacingS5 = 46;
  static const double spacingS6 = 56;
  static const double spacingS7 = 64;
  static const double spacingS8 = 73;
  static const double spacingS9 = 80;
  static const double spacingS10 = 88;
  static const double spacingS11 = 91;
  static const double spacingS12 = 99;
  static const double spacingS13 = 111;
  static const double spacingS14 = 184;
  static const double spacingS15 = 192;
  static const double spacingS16 = 197;
  static const double spacingS17 = 215;
  static const double spacingS18 = 229;
  static const double spacingS19 = 248;
  static const double spacingS20 = 252;
  static const double spacingS21 = 380;
  static const double radiusR0 = 2;
  static const double radiusR1 = 6;
  static const double radiusR2 = 50;
  static const double radiusR3 = 1280;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF146EF5);
  static const Color brandSecondary = Color(0xFF6CA7FF);
  static const Color neutralN100 = Color(0xFF080808);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF5A5A5A);
  static const Color neutralN400 = Color(0xFFD8D8D8);
  static const Color neutralN500 = Color(0xFFF0F0F0);
  static const Color neutralN600 = Color(0xFF1A1A1A);
  static const Color neutralN700 = Color(0xFF6B7280);
  static const Color neutralN800 = Color(0xFF292929);
  static const Color neutralN900 = Color(0xFF464646);
  static const Color neutralN1000 = Color(0xFF808080);
  static const Color neutralN1100 = Color(0xFF171717);
  static const Color neutralN1200 = Color(0xFF363636);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFF146EF5);
  static const Color backgroundBg2 = Color(0xFF080808);
  static const Color backgroundBg3 = Color(0xFF222222);
  static const Color backgroundBg4 = Color(0xFF171717);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF080808);
  static const Color textText2 = Color(0xFFFFFFFF);
  static const Color textText3 = Color(0xFF5A5A5A);
  static const Color textText4 = Color(0xFF808080);
  static const Color textText5 = Color(0xFFFFA666);
  static const Color textText6 = Color(0xFF6CA7FF);
  static const Color textText7 = Color(0xFF60ED76);
  static const Color textText8 = Color(0xFF146EF5);
  static const Color textText9 = Color(0xFF1A1A1A);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
