// Generated by designlang v7.0.0
// Source: https://sentry.io
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF150F23)
    val ActionSecondary = Color(0xFF9ECBFF)
    val SurfaceDefault = Color(0xFF1F1633)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF150F23)
    val BrandSecondary = Color(0xFF9ECBFF)
    val NeutralN100 = Color(0xFFFFFFFF)
    val NeutralN200 = Color(0xFFD4D4D4)
    val NeutralN300 = Color(0xFFE1E4E8)
    val NeutralN400 = Color(0xFF6A737D)
    val NeutralN500 = Color(0xFF000000)
    val NeutralN600 = Color(0xFF1A1A1A)
    val NeutralN700 = Color(0xFFEFEFEF)
    val NeutralN800 = Color(0xFF584674)
    val NeutralN900 = Color(0xFFC1C1C1)
    val BackgroundBg0 = Color(0xFF1F1633)
    val BackgroundBg1 = Color(0xFF150F23)
    val BackgroundBg2 = Color(0xFF422082)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFF1A1A1A)
    val TextText3 = Color(0xFF6A5FC1)
    val TextText4 = Color(0xFF1F1633)
    val TextText5 = Color(0xFF03060A)
    val TextText6 = Color(0xFF4E2A9A)
    val TextText7 = Color(0xFF010205)
    val TextText8 = Color(0xFF090D16)
    val TextText9 = Color(0xFFEFEFEF)
    val SpacingS0 = 2.dp
    val SpacingS1 = 16.dp
    val SpacingS2 = 20.dp
    val SpacingS3 = 24.dp
    val SpacingS4 = 32.dp
    val SpacingS5 = 35.dp
    val SpacingS6 = 40.dp
    val SpacingS7 = 44.dp
    val SpacingS8 = 56.dp
    val SpacingS9 = 64.dp
    val SpacingS10 = 72.dp
    val SpacingS11 = 83.dp
    val SpacingS12 = 160.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 6.dp
    val RadiusR2 = 10.dp
    val RadiusR3 = 13.dp
    val RadiusR4 = 16.dp
    val RadiusR5 = 50.dp
}
