// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://webflow.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x146EF5)
  static let actionSecondary = Color(hex: 0x6CA7FF)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 23
  static let spacingS2: CGFloat = 31
  static let spacingS3: CGFloat = 37
  static let spacingS4: CGFloat = 40
  static let spacingS5: CGFloat = 46
  static let spacingS6: CGFloat = 56
  static let spacingS7: CGFloat = 64
  static let spacingS8: CGFloat = 73
  static let spacingS9: CGFloat = 80
  static let spacingS10: CGFloat = 88
  static let spacingS11: CGFloat = 91
  static let spacingS12: CGFloat = 99
  static let spacingS13: CGFloat = 111
  static let spacingS14: CGFloat = 184
  static let spacingS15: CGFloat = 192
  static let spacingS16: CGFloat = 197
  static let spacingS17: CGFloat = 215
  static let spacingS18: CGFloat = 229
  static let spacingS19: CGFloat = 248
  static let spacingS20: CGFloat = 252
  static let spacingS21: CGFloat = 380

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 6
  static let radiusR2: CGFloat = 50
  static let radiusR3: CGFloat = 1280
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x146EF5)
  static let brandSecondary = Color(hex: 0x6CA7FF)
  static let neutralN100 = Color(hex: 0x080808)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x5A5A5A)
  static let neutralN400 = Color(hex: 0xD8D8D8)
  static let neutralN500 = Color(hex: 0xF0F0F0)
  static let neutralN600 = Color(hex: 0x1A1A1A)
  static let neutralN700 = Color(hex: 0x6B7280)
  static let neutralN800 = Color(hex: 0x292929)
  static let neutralN900 = Color(hex: 0x464646)
  static let neutralN1000 = Color(hex: 0x808080)
  static let neutralN1100 = Color(hex: 0x171717)
  static let neutralN1200 = Color(hex: 0x363636)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0x146EF5)
  static let backgroundBg2 = Color(hex: 0x080808)
  static let backgroundBg3 = Color(hex: 0x222222)
  static let backgroundBg4 = Color(hex: 0x171717)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x080808)
  static let textText2 = Color(hex: 0xFFFFFF)
  static let textText3 = Color(hex: 0x5A5A5A)
  static let textText4 = Color(hex: 0x808080)
  static let textText5 = Color(hex: 0xFFA666)
  static let textText6 = Color(hex: 0x6CA7FF)
  static let textText7 = Color(hex: 0x60ED76)
  static let textText8 = Color(hex: 0x146EF5)
  static let textText9 = Color(hex: 0x1A1A1A)
}

// typography.body: family=WF Visual Sans Variable size=74.8571px weight=600 lineHeight=77.8514px
