// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://sentry.io
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x150F23)
  static let actionSecondary = Color(hex: 0x9ECBFF)
  static let surfaceDefault = Color(hex: 0x1F1633)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 2
  static let spacingS1: CGFloat = 16
  static let spacingS2: CGFloat = 20
  static let spacingS3: CGFloat = 24
  static let spacingS4: CGFloat = 32
  static let spacingS5: CGFloat = 35
  static let spacingS6: CGFloat = 40
  static let spacingS7: CGFloat = 44
  static let spacingS8: CGFloat = 56
  static let spacingS9: CGFloat = 64
  static let spacingS10: CGFloat = 72
  static let spacingS11: CGFloat = 83
  static let spacingS12: CGFloat = 160

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 6
  static let radiusR2: CGFloat = 10
  static let radiusR3: CGFloat = 13
  static let radiusR4: CGFloat = 16
  static let radiusR5: CGFloat = 50
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x150F23)
  static let brandSecondary = Color(hex: 0x9ECBFF)
  static let neutralN100 = Color(hex: 0xFFFFFF)
  static let neutralN200 = Color(hex: 0xD4D4D4)
  static let neutralN300 = Color(hex: 0xE1E4E8)
  static let neutralN400 = Color(hex: 0x6A737D)
  static let neutralN500 = Color(hex: 0x000000)
  static let neutralN600 = Color(hex: 0x1A1A1A)
  static let neutralN700 = Color(hex: 0xEFEFEF)
  static let neutralN800 = Color(hex: 0x584674)
  static let neutralN900 = Color(hex: 0xC1C1C1)
  static let backgroundBg0 = Color(hex: 0x1F1633)
  static let backgroundBg1 = Color(hex: 0x150F23)
  static let backgroundBg2 = Color(hex: 0x422082)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x1A1A1A)
  static let textText3 = Color(hex: 0x6A5FC1)
  static let textText4 = Color(hex: 0x1F1633)
  static let textText5 = Color(hex: 0x03060A)
  static let textText6 = Color(hex: 0x4E2A9A)
  static let textText7 = Color(hex: 0x010205)
  static let textText8 = Color(hex: 0x090D16)
  static let textText9 = Color(hex: 0xEFEFEF)
}

// typography.body: family=Rubik size=88px weight=700 lineHeight=105.6px
