// Generated by designlang v7.0.0
// Source: https://duolingo.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFD7FFB8);
  static const Color actionSecondary = Color(0xFF0000EE);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 8;
  static const double spacingS2 = 23;
  static const double spacingS3 = 40;
  static const double spacingS4 = 48;
  static const double spacingS5 = 64;
  static const double spacingS6 = 80;
  static const double spacingS7 = 96;
  static const double spacingS8 = 140;
  static const double spacingS9 = 185;
  static const double radiusR0 = 2;
  static const double radiusR1 = 12;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFD7FFB8);
  static const Color brandSecondary = Color(0xFF0000EE);
  static const Color neutralN100 = Color(0xFF3C3C3C);
  static const Color neutralN200 = Color(0xFF777777);
  static const Color neutralN300 = Color(0xFF000000);
  static const Color neutralN400 = Color(0xFF4B4B4B);
  static const Color neutralN500 = Color(0xFFAFAFAF);
  static const Color neutralN600 = Color(0xFFFFFFFF);
  static const Color neutralN700 = Color(0xFFE5E5E5);
  static const Color neutralN800 = Color(0xFF808080);
  static const Color neutralN900 = Color(0xFFC1C1C1);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFFDDF4FF);
  static const Color backgroundBg2 = Color(0xFF100F3E);
  static const Color backgroundBg3 = Color(0xFF58CC02);
  static const Color backgroundBg4 = Color(0xFF000000);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF3C3C3C);
  static const Color textText2 = Color(0xFF0000EE);
  static const Color textText3 = Color(0xFFAFAFAF);
  static const Color textText4 = Color(0xFF4B4B4B);
  static const Color textText5 = Color(0xFFFFFFFF);
  static const Color textText6 = Color(0xFF1CB0F6);
  static const Color textText7 = Color(0xFF777777);
  static const Color textText8 = Color(0xFF58CC02);
  static const Color textText9 = Color(0xFF042C60);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
