// Generated by designlang v7.0.0
// Source: https://ramp.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF000000)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF000000)
    val NeutralN100 = Color(0xFF000000)
    val TextText0 = Color(0xFF000000)
    val SpacingS0 = 8.dp
    val SpacingS1 = 13.dp
}
