// Generated by designlang v7.0.0
// Source: https://replit.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF0051C3)
    val ActionSecondary = Color(0xFFDE5052)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF0051C3)
    val BrandSecondary = Color(0xFFDE5052)
    val NeutralN100 = Color(0xFF404040)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFF595959)
    val NeutralN400 = Color(0xFFFFFFFF)
    val NeutralN500 = Color(0xFFEBEBEB)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFFEBEBEB)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF404040)
    val TextText2 = Color(0xFFFFFFFF)
    val TextText3 = Color(0xFF595959)
    val TextText4 = Color(0xFF0051C3)
    val SpacingS0 = 3.dp
    val SpacingS1 = 23.dp
    val SpacingS2 = 53.dp
    val SpacingS3 = 160.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 5.dp
}
