// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://resend.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xD6EBFD)
  static let actionSecondary = Color(hex: 0x00A3FF)
  static let surfaceDefault = Color(hex: 0x000000)
  static let textBody = Color(hex: 0xFFFFFF)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 20
  static let spacingS2: CGFloat = 24
  static let spacingS3: CGFloat = 28
  static let spacingS4: CGFloat = 40
  static let spacingS5: CGFloat = 48
  static let spacingS6: CGFloat = 62
  static let spacingS7: CGFloat = 80
  static let spacingS8: CGFloat = 96
  static let spacingS9: CGFloat = 104
  static let spacingS10: CGFloat = 144
  static let spacingS11: CGFloat = 150
  static let spacingS12: CGFloat = 221
  static let spacingS13: CGFloat = 380

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 4
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 12
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 24
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xD6EBFD)
  static let brandSecondary = Color(hex: 0x00A3FF)
  static let neutralN100 = Color(hex: 0xF0F0F0)
  static let neutralN200 = Color(hex: 0xA1A4A5)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0xF1F7FE)
  static let neutralN500 = Color(hex: 0x464A4D)
  static let neutralN600 = Color(hex: 0x6C6C6C)
  static let neutralN700 = Color(hex: 0x000000)
  static let neutralN800 = Color(hex: 0xE5EDFD)
  static let neutralN900 = Color(hex: 0x70757E)
  static let neutralN1000 = Color(hex: 0x262A2D)
  static let neutralN1100 = Color(hex: 0xCCCCCC)
  static let backgroundBg0 = Color(hex: 0x000000)
  static let backgroundBg1 = Color(hex: 0xFFFFFF)
  static let textText0 = Color(hex: 0xFFFFFF)
  static let textText1 = Color(hex: 0xF0F0F0)
  static let textText2 = Color(hex: 0xF1F7FE)
  static let textText3 = Color(hex: 0xA1A4A5)
  static let textText4 = Color(hex: 0xFFC446)
  static let textText5 = Color(hex: 0xFCFDFF)
  static let textText6 = Color(hex: 0xEBECED)
  static let textText7 = Color(hex: 0x464A4D)
  static let textText8 = Color(hex: 0x6C6C6C)
  static let textText9 = Color(hex: 0xA0A0A0)
}

// typography.body: family=inter size=96px weight=400 lineHeight=96px
