// Generated by designlang v7.0.0
// Source: https://planetscale.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFF2B600)
    val ActionSecondary = Color(0xFFF35815)
    val SurfaceDefault = Color(0xFFFAFAFA)
    val TextBody = Color(0xFF414141)
    val BrandPrimary = Color(0xFFF2B600)
    val BrandSecondary = Color(0xFFF35815)
    val NeutralN100 = Color(0xFF414141)
    val NeutralN200 = Color(0xFFC1C1C1)
    val NeutralN300 = Color(0xFF737373)
    val NeutralN400 = Color(0xFFFFFFFF)
    val NeutralN500 = Color(0xFF000000)
    val NeutralN600 = Color(0xFF111111)
    val NeutralN700 = Color(0xFFEBEBEB)
    val BackgroundBg0 = Color(0xFFFAFAFA)
    val BackgroundBg1 = Color(0xFF111111)
    val TextText0 = Color(0xFF414141)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFF111111)
    val TextText3 = Color(0xFFC1C1C1)
    val TextText4 = Color(0xFF000000)
    val TextText5 = Color(0xFF0B6EC5)
    val TextText6 = Color(0xFF737373)
    val TextText7 = Color(0xFFFAFAFA)
    val SpacingS0 = 4.dp
    val SpacingS1 = 80.dp
    val SpacingS2 = 96.dp
    val RadiusR0 = 9999.dp
}
